---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Code Coverage"
consumes:
  - application/json
produces:
  - application/json
paths:

  /example:
    get:
      operationId: "shipit_code_coverage_backend.api.example"
      responses:
        200:
          description: Example

